In [6]:
#how first step you need import the library numpy
import numpy as np

In [7]:
#now we can create a matrix, whith anything values
#every value is a number (important)
#vector
vector = np.array([3,4,5])

#matriz
matriz = np.array([[1,2,3],[4,5,6]])
#with ndim we can see the dimension of the matrix
print (vector, np.ndim(vector))
print("""
""")
print (matriz, np.ndim(matriz))

[3 4 5] 1


[[1 2 3]
 [4 5 6]] 2


In [12]:
#in a array of two dimensions
arraytwo = np.array([[11,12,13],[14,15,16]])
#print(arraytwo)
#As well  you can put the dimensions without "print"
#np.ndim(arraytwo)
#if you want add a dimension 
arraythree = np.array([[[11,12,13],[17,18,19]],[[11,12,13],[17,18,19]]], ndmin=6)
print (arraythree, np.ndim(arraythree))


[[[[[[11 12 13]
     [17 18 19]]

    [[11 12 13]
     [17 18 19]]]]]] 6


In [13]:
#well, now if you want delet dimensions
print (arraythree)
#if you need wipe
print("clean...")
arraythre2 = np.squeeze(arraythree)
print (arraythre2)

[[[[[[11 12 13]
     [17 18 19]]

    [[11 12 13]
     [17 18 19]]]]]]
clean...
[[[11 12 13]
  [17 18 19]]

 [[11 12 13]
  [17 18 19]]]


In [30]:
#case partifular, array 2 dimensions but you need add one more, use "axis"
rray = np.array([[1,2,3],[1,2,3],[1,2,3]])
print (rray, rray.ndim)

print ("add a file")
rray = np.expand_dims([[1,2,3],[1,2,3],[1,2,3]], axis =0)
print (rray)
#check dimensions
rray.ndim

[[1 2 3]
 [1 2 3]
 [1 2 3]] 2
add a file
[[[1 2 3]
  [1 2 3]
  [1 2 3]]]


3